version: 2.1
jobs:
  build:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache curl
      - run:
          name: Build image
          command: |
            docker build --tag registry.heroku.com/$HEROKU_APP_NAME/web --file ./Dockerfile "."
      - run:
          name: Push the image
          command: |
            docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
      - run:
          name: Deploy to Heroku
          command: |
            chmod +x .circleci/release.sh
            .circleci/release.sh
      - run:
          name: Push to Docker Hub
          command: |
            docker logout
            docker tag registry.heroku.com/$HEROKU_APP_NAME/web $DOCKER_HUB_REPO:latest
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_TOKEN
            docker push $DOCKER_HUB_REPO:latest
