version: 2.1
orbs:
  deploy-to-heroku: betterdoc/deploy-to-heroku@4.0.0
jobs:
  build:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache curl
      - run:
          name: Build image
          command: |
            docker build --tag registry.heroku.com/$HEROKU_APP_NAME/web --file ./Dockerfile "."
      - run:
          name: Deploy the image
          command: |
            docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
      - run:
          name: Deploy to Heroku
          command: |
            chmod +x .circleci/release.sh
            .circleci/release.sh